{
  [firebase]
type = "service_account"
project_id = "trading-bot-bbb5f"
private_key_id = "ad179bea8e9cde8428c6aa1f4aec841052a98881"

private_key = """
-----BEGIN PRIVATE KEY-----
\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDeELHfh+2KL7PB\nuMmlOsv2LviPe60OVsZdGBhMbs5AEVpeZry7mhQSr72A3Ka9eaSK8YPmhlwluhDk\nKCwpXEdCBx4DVs1cOfxGfuhDwbrFldOmrq0ybJeXWXBIR/tzUO9b+qWP+XgHOflj\nCUlB6Rrrh/IXk4ZskMuYfPiJ2pVxRIihYadXxOCByWSMdFJiX60efcc94S82gXPf\nfZe+ws45YAiOOrHWiTahoD0ykTVUP3AyZ10hWPHu5gJMsS6jk836QyTuEjDqLqZn\n/hj5vjxh65ecWC+zjBJfmz+4ps+smYQCy9bt3ERDRBWeHWbwkgsEpJF+tBBltQVp\nGXxUkA5hAgMBAAECggEAWMQJphW6sTMyQqywBhlDsIvEFe7VFVdAgbQA+oSMc3W8\nTuH4bXFAttuC/8Cz8iduy4+RLxPkP7xpxhn81Seq4EziBWmsO0J+glt2UqddFmA2\ns3k9iFt6GSjKRkpnzAe9NmIxziRlg1X8R0dN/kfE2AOGlUAGSt1yVOkXnFtAw35n\n7d1EgiRkpBn2pYsTHAF1kZDvyxczyxa77aO9wz7Ogsx7ZhVg6c56gTPvOExfnu4C\n8/78+z6wde6nD3vzlaAmjzsbgOpQPK8MacvsMtbNXj2/p+zWCyJA2TOGpxWTEnYh\nYS9ZIZpzNSTFUe9n8y4dXBbImfD7paRjxaYl0zx+JQKBgQD4NRhDFrgrrTV7h38g\nIdbFFdaX5JGccmfPKDXEJuZDQKqrwr33fNafH+5+I8iGx1klivnOh78/rfDoXjDs\nZJcN242oReiQ7SmMXADH1nIaVd+Ue6SB9hEaeEqiHVrMzifOEs58if6Mq8MB0Ff7\npAYdHqFw7GlISva/RBeimzvnywKBgQDlCX0cnFn3gCuOasuykaNEE7rNyKoBbCzi\ncVXEdNKqZwkgiNV1b4ZSNLcRZ7HOXYwqIeIC8cmBHQ23ofS43TNL7QLf+Hs6+VzE\nM0ontNpdMn1AoHeonq9+X4cbOx4ZrTrXguf/eInGzRq9QUy8FE62JYeP2WNm0SYt\nQ67Da5QlAwKBgQDWmlGX8BTc7q3HWKf5yEhBr1gTjHS5p9FJs6KJLnj4vPjT+VT2\nnuGSQ7GZLqc6oTHa3AaRI52gGWyp/IagXXidaq9YRtmGNQgva3zhS/DsBEODxkO+\nelrfYBJniKnxWm3gJzKRS17jkb7R2qm30WHX25wKXt3Iu8gMJ3uoBEAPcQKBgAIn\nHK3wKkhRRBeKmW+MPuSc6tyUTkTFJ4bZWd0G3BQN8+ACaT85VSHgrPfU6a7u4ipj\nNySf8SztgPuA4jP6oEjOaYCBbWcYgO63LLNC1+qYVuUMnRNQqoWdkD+JRrcnEa6E\n5HlaQLFFrEKrInWCG1tK7wNDH9QPkzRJtpLPqAzRAoGAfPftIVcyFhccfOu4X1Fm\nSkVstcZaNGMo5pko5XUxwyBc5PJWxw0hg5yBeNFHjqeoJ3w7F/FB/uqs+IxhTa52\nMdL+REaqxYwnl/YT6HCXJwIp9LNQF+0UyvONsY5C2gOmGJBr9JVrV8cvDWHAnTK2\nJsiWuxfjq+8M8FFix7bXqUk=\n-----END PRIVATE KEY-----
"""

client_email = "firebase-adminsdk-xxx@bank-cloud.iam.gserviceaccount.com"
client_id = "103690618154521803821"

auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"



[google_vision]
type = "service_account"
project_id = "trading-bot-bbb5f"
private_key_id = "6a74c38764355842a2ceb4fdf10256b4fe0cb58c"

private_key = """
-----BEGIN PRIVATE KEY-----
\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDGunF3cpX3q3Er\nkes5PjiT8c2zNlg2aJRcSIzJdI6RKYJH7eHJnfUW1leHKCTQZVeLzZv+wySEvksX\n0je1Cs90FDeFF+phN9sH7R4FAE8XBeZP1yfB2BoVDBqJ9iVZNxjjeaGZJ8jX+hHS\n2kzu9ehhOX95VNs2cAv0MgIyBK6IinT+4H13CDWyLddYPvGwWC4eVp54mCKKQAra\nU4f/9Tyxil/r/TE6ru81h4Bnr7/xeZfpbNAfChZSfz0OebP8I80mqzCZGFekb7nD\nfeiZ70M17WCWrj6T6G5zsQe8LoVYOWJd8XEWu/n1YUZIDx8paXVn6+9F5+imvRkq\ndHzmtQajAgMBAAECggEABeWChPpu+mFpdDEAkcfyWPNM8mw+Nb/gCGYmBWWxVNdh\nsTHQHW2G+jHcRZlGO24zsVydEp65vjwJfkzieLtaFVLQpKU6yGkVO7ObiFHbQqQf\nNK91l9W9bwvXMVkXVXksz0+dwxyRQczlJxe11/CgKo5ZKbSzKNTY3wVT6L+PrlIo\nzd6ss5auhQxw7htOzA7J/yu67lbqBtn6oioX6qldEMVYvA+n6Qo0LFQA/8rVeMj/\nUXcR1usxvPwR/CESRWJDP7DFTwS7bC0RvAoQbMxySiwLoifkqcgoPzvCMHHbiR1K\nasOSfiXMmHbD6MwfNN1+kiYZE+ytPLR9WI9OW6MzQQKBgQDnQ2pZhDsea320SzAW\nK5g3Sn3gwsjVY7AztVLBs5gu0KABVtLGYpspVfy/M6sJA+aLmARXp8NvhRZVPnQI\n4rTwXe6GEsaMp8m2Bfw9jJzkO1B8+RUVB+sAHhtuYwQumzs8rgRGB1cxqcxooo7p\n4couInk8C8WoVpVNs/yu5aE0wQKBgQDb/CJ0e58itmEz+8j8juSd52x1qapxsk1P\nuqvMOVoDkgDqcgaFPX5HkKk5Mn7nEKvyZZrIIe/N2QrDVk9LjxMOFGJdJtRHIpYd\nSsvwvRpkHF8r4cRXMnmN9SV+HTXxrfNbTPRIbsmaKVujHa3Pj480JnHHiZyft5EG\nFplMWKWgYwKBgGXKSI8qIpNbILMwvPOlMJR1lz5MvfUesbmwv8I+eGdysFqmipOD\nZ2QkUuEdrtSDAQDEYnTqhJ0baR8QJCadEqMR1SDyNq5GVARoUgQNVikm6mB3ig39\ntDQTDGPj9T1GWiZ1ObBRHtHfOPd9RYYwObtgtRf23oMfyQuwgzHAJNqBAoGBAMkO\nhocjvWxCeFDEnQuHphdTvmND8I39wn9OQ1piSIze0ot0L9VzQIk0BBZMuoOBT0Y5\n6t9jdQMUjau+pLaQS4AgzU4KARYK3FxlUkPy8b3x2GII9CQl88b0+ZFsLTN4IuWd\nTd8tsoB9sE1DAOqlcOLfCDqw4T9wzNFdsjp/AtG1AoGBAMkTdo+eNdMsqFh1wiiz\nzaOATMHdEx/l0kZ7eeZqgn2Yf7qPcSt3FQ+K2BvWVy1eW0lHCAv+o7c2Rse/QPLv\n8WsvDuwkmEWNr001R3CecK2AVXdwUj5scREszlgzi1HrzWquyrnkWXymoXOsjGiw\nKKlitGBUVAk4T2CRHr/PBpjk\n
-----END PRIVATE KEY-----
"""

client_email = "vision-ocr@trading-bot-bbb5f.iam.gserviceaccount.com"
client_id = "100827859750158713826"

auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
}
